# Generated by Django 4.2.7 on 2025-11-11 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("record_index", models.IntegerField()),
                ("error_type", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "ingestion_errors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ingestion_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("grade", models.CharField(max_length=20)),
                ("section", models.CharField(blank=True, max_length=10)),
                ("roll_number", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="India", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.ingestionjob",
                    ),
                ),
            ],
            options={
                "db_table": "student_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["task_id", "status"], name="ingestion_j_task_id_7f6cfe_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["created_at"], name="ingestion_j_created_701f2d_idx"),
        ),
        migrations.AddField(
            model_name="ingestionerror",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="ingestion.ingestionjob",
            ),
        ),
        migrations.AddIndex(
            model_name="studentrecord",
            index=models.Index(
                fields=["student_id", "email"], name="student_rec_student_0ee0c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentrecord",
            index=models.Index(fields=["grade", "section"], name="student_rec_grade_c8cdfa_idx"),
        ),
        migrations.AddIndex(
            model_name="studentrecord",
            index=models.Index(fields=["job", "created_at"], name="student_rec_job_id_ec9f58_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentrecord",
            unique_together={("job", "student_id")},
        ),
        migrations.AddIndex(
            model_name="ingestionerror",
            index=models.Index(fields=["job", "error_type"], name="ingestion_e_job_id_55cdff_idx"),
        ),
    ]
